# Generated by Django 5.0.6 on 2024-05-17 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания:')),
                ('description', models.TextField(verbose_name='Описание задания:')),
                ('due_date', models.DateField(verbose_name='Срок сдачи:')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_video', models.FileField(max_length=5242880, upload_to='lectures/')),
                ('title', models.CharField(max_length=100, verbose_name='Title:')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название:')),
                ('description', models.TextField(verbose_name='Описание:')),
                ('start_date', models.DateField(verbose_name='Дата начала:')),
                ('end_date', models.DateField(verbose_name='Дата окончания:')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображения:')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
                ('lectures', models.ManyToManyField(related_name='Лекции', to='all.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user:')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all.course', verbose_name='course:')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
